title: "Core Cognition"
description: "Core Knowledge Deficits in Multi-Modal Language Models"
url: "https://williamium3000.github.io"
baseurl: "/core-knowledge"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  authors:
    output: false

# Exclude files
exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - tailwind.config.js
  - postcss.config.js
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - README.md

# Social links
github_username: williamium3000/core-knowledge
paper_url: "https://arxiv.org/abs/2410.10855"
huggingface_url: "https://huggingface.co/datasets/williamium/CoreCognition"
pypi_url: ""
code_url: https://github.com/williamium3000/core-knowledge
# Project info
version: "1.0.1"
license: "Apache-2.0"

# GitHub Pages specific settings
github: [metadata]
kramdown:
  input: GFM
  syntax_highlighter: rouge 
